-- AlterTable
ALTER TABLE "Address" ALTER COLUMN "zipCode" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Branch" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Info" ALTER COLUMN "cnpj" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "phoneNumber" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "ProductCategories" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Products" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);
