#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff HEAD --quiet || 
(
  echo "You have uncommitted changes. Please commit them and try again."
  false;
)

npm run type-check || 
(
  echo "Type checking failed. Please fix the errors and try again."
  false;
)

npm run format || 
(
  echo "Formatting failed. Please fix the errors and try again."
  false;
)

npm run lint || 
(
  echo "Linting failed. Please fix the errors and try again."
  false;
)

npm run test || 
(
  echo "Tests failed. Please fix the errors and try again."
  false;
)